[project]
authors = ["cyril0124 <211998078@qq.com>"]
channels = [
    "conda-forge", 
    "https://prefix.dev/vidlg" # libassert
]
description = "pixi.toml for Verilua"
name = "Verilua"
platforms = ["linux-64"]
version = "0.1.0"

[activation]
scripts = ["pixi_env_setup.sh"]

[tasks]
init = "xmake r -F xmake-pixi.lua init"
build = "xmake b -F xmake-pixi.lua -v"
clean = "xmake c -F xmake-pixi.lua -v"
install = "xmake r -F xmake-pixi.lua install"

[dependencies]
libassert = ">=2.1.3,<3"
mimalloc = ">=2.1.7,<3"
elfio = ">=3.10,<4"
fmt = ">=11.0.2,<12"
inja = ">=3.3.0,<4"
cpp-argparse = ">=3.1,<4"
vcpkg = ">=2023.4.15,<2024"
boost-cpp = ">=1.85.0,<2"
