---@diagnostic disable: unnecessary-assert, unresolved-require

local json = require "json"
local stringx = require "pl.stringx"
local SymbolHelper = require "verilua.utils.SymbolHelper"

local cfg = _G.cfg
local f = string.format

---@class (exact) verilua.utils.DpiExporter.signal_info
---@field hierPath string Raw hierarchical path from dpi_exporter (exporter top)
---@field bitWidth integer
---@field vpiTypeStr string
---@field handleId integer

---@class (exact) verilua.utils.DpiExporter.meta_info
---@field cmdLine string
---@field configFileContent string
---@field dpiFilePath string
---@field exportedSignalInfos verilua.utils.DpiExporter.signal_info[]
---@field filelist string[]
---@field insertModuleName string
---@field topModuleName string

---@class (exact) verilua.utils.DpiExporter
---@field private initialized boolean
---@field private meta_info verilua.utils.DpiExporter.meta_info
---@field private dpi_exporter_top string
---@field private export_map table<string, verilua.utils.DpiExporter.signal_info>
---@field private symbol_cache_idx number
---@field private symbol_cache table<number, function>
---@field private _dummy_vpi_linked boolean?
---@field init fun(self: verilua.utils.DpiExporter, meta_file?: string): verilua.utils.DpiExporter `meta_file` is a json file generated by `dpi_exporter`
---@field try_init fun(self: verilua.utils.DpiExporter, meta_file?: string): boolean Try to initialize the exporter, return true if success
---@field dummy_vpi_linked fun(self: verilua.utils.DpiExporter): boolean Cached probe for dummy_vpi marker symbol
---@field lookup fun(self: verilua.utils.DpiExporter, hierpath: string): verilua.utils.DpiExporter.signal_info? Static signal info or nil if not exported
---@field fetch_trigger_func fun(self: verilua.utils.DpiExporter, trigger_name: string?): fun(): boolean
---@field fetch_get_value_func fun(self: verilua.utils.DpiExporter, hierpath: string): fun(): number
---@field fetch_get64_value_func fun(self: verilua.utils.DpiExporter, hierpath: string): fun(): number
---@field fetch_get_vec_value_func fun(self: verilua.utils.DpiExporter, hierpath: string): function
---@field fetch_get_hex_str_value_func fun(self: verilua.utils.DpiExporter, hierpath: string): function
local DpiExporter = {
    initialized = false,
    ---@diagnostic disable-next-line: missing-fields
    meta_info = {},
    dpi_exporter_top = "",
    export_map = {},
    symbol_cache_idx = 0,
    symbol_cache = {},
    _dummy_vpi_linked = nil,
}

local function to_hierpath_name(hierpath)
    local t = stringx.replace(hierpath, ".", "_")
    t = stringx.replace(t, "[", "_")
    t = stringx.replace(t, "]", "_")
    return t
end

---@param signal_hierpath string
---@param dpi_top string
---@return string
local function normalize_hierpath(signal_hierpath, dpi_top)
    -- Add `@` so only a leading top module name is replaced.
    return stringx.replace(
        "@" .. signal_hierpath,
        "@" .. dpi_top,
        cfg.top .. ".u_" .. dpi_top
    )
end

-- Auto detect meta_file from linked dpi_exporter (nil if not linked).
-- Do NOT touch ffi.C.<missing>: LuaJIT resolves it as undefined symbol and aborts.
---@return string?
local function try_get_meta_file()
    if SymbolHelper.get_global_symbol_addr("dpi_exporter_get_meta_info_file_path") == 0 then
        return nil
    end
    local func = SymbolHelper.ffi_cast("char *(*)()", "dpi_exporter_get_meta_info_file_path")
    ---@diagnostic disable-next-line: call-non-callable
    return ffi.string(func())
end

function DpiExporter:init(meta_file)
    if self.initialized then
        return self
    end

    if not meta_file then
        meta_file = try_get_meta_file()
        assert(
            meta_file,
            "[DpiExporter] dpi_exporter_get_meta_info_file_path not linked; "
            .. "build with dpi_exporter or pass meta_file to init()/try_init()"
        )
    end

    local file = io.open(meta_file, "r")
    if not file then
        error("[DpiExporter] Failed to open meta file: " .. meta_file)
    else
        self.meta_info = json.decode(file:read("*a"))
        assert(self.meta_info, "[DpiExporter] Failed to decode meta file: " .. meta_file)
        file:close()
    end

    -- Check if the dpi function file exists
    local dpi_func_file = self.meta_info.dpiFilePath
    local file2 = io.open(dpi_func_file, "r")
    if not file2 then
        error("[DpiExporter] Failed to open dpi function file: " .. dpi_func_file)
    else
        file2:close()
    end

    self.dpi_exporter_top = assert(
        self.meta_info.topModuleName,
        "[DpiExporter] Failed to get top module name from meta file: " .. meta_file
    ) --[[@as string]]

    local infos = self.meta_info.exportedSignalInfos
    assert(
        type(infos) == "table",
        "[DpiExporter] meta missing exportedSignalInfos; regenerate with current dpi_exporter: " .. meta_file
    )

    -- O(1) lookup by raw exporter path and by normalized sim fullpath.
    self.export_map = {}
    for _, info in ipairs(infos) do
        assert(type(info) == "table", "[DpiExporter] invalid exportedSignalInfos entry")
        assert(type(info.hierPath) == "string", "[DpiExporter] exportedSignalInfos.hierPath missing")
        assert(type(info.bitWidth) == "number", "[DpiExporter] exportedSignalInfos.bitWidth missing: " .. info.hierPath)
        assert(type(info.vpiTypeStr) == "string",
            "[DpiExporter] exportedSignalInfos.vpiTypeStr missing: " .. info.hierPath)
        assert(type(info.handleId) == "number", "[DpiExporter] exportedSignalInfos.handleId missing: " .. info.hierPath)

        self.export_map[info.hierPath] = info
        self.export_map[normalize_hierpath(info.hierPath, self.dpi_exporter_top)] = info
    end

    self.initialized = true

    -- Mark as enabled, used by `LuaCallableHDL.lua`
    -- Notice: Call `DpiExporter:init()` before creating any `CallableHDL` if you want to access the signal by dpi_exporter API.
    cfg.enable_dpi_exporter = true

    return self
end

function DpiExporter:try_init(meta_file)
    if not meta_file then
        meta_file = try_get_meta_file()
    end
    if not meta_file then
        return false
    end

    local file = io.open(meta_file, "r")
    if not file then
        return false
    end
    file:close()
    self:init(meta_file)
    return true
end

function DpiExporter:dummy_vpi_linked()
    if self._dummy_vpi_linked == nil then
        self._dummy_vpi_linked = SymbolHelper.get_global_symbol_addr("vl_dummy_vpi_linked") ~= 0
    end
    return self._dummy_vpi_linked
end

function DpiExporter:lookup(hierpath)
    assert(self.initialized, "DpiExporter not initialized")
    return self.export_map[hierpath]
end

function DpiExporter:fetch_trigger_func(trigger_name)
    local trigger_func_name = "dpi_exporter_sensitive_trigger"
    if trigger_name then
        trigger_func_name = "dpi_exporter_sensitive_trigger_" .. trigger_name
    end
    local func = SymbolHelper.try_ffi_cast(
        f("bool %s();", trigger_func_name)
    ) --[[@as fun(): boolean]]
    self.symbol_cache_idx = self.symbol_cache_idx + 1
    self.symbol_cache[self.symbol_cache_idx] = func -- Keep the function alive(avoid gc)

    return self.symbol_cache[self.symbol_cache_idx]
end

function DpiExporter:fetch_get_value_func(hierpath)
    local info = assert(
        self:lookup(hierpath),
        "[DpiExporter] Signal " .. hierpath .. " is not exported"
    )

    local func_name = f("VERILUA_DPI_EXPORTER_%s_GET", to_hierpath_name(info.hierPath))
    local func = SymbolHelper.try_ffi_cast(
        f("uint32_t %s();", func_name)
    ) --[[@as function]]
    self.symbol_cache_idx = self.symbol_cache_idx + 1
    self.symbol_cache[self.symbol_cache_idx] = func -- Keep the function alive(avoid gc)

    return self.symbol_cache[self.symbol_cache_idx]
end

function DpiExporter:fetch_get64_value_func(hierpath)
    local info = assert(
        self:lookup(hierpath),
        "[DpiExporter] Signal " .. hierpath .. " is not exported"
    )

    local func_name = f("VERILUA_DPI_EXPORTER_%s_GET64", to_hierpath_name(info.hierPath))
    local func = SymbolHelper.try_ffi_cast(
        f("uint64_t %s();", func_name)
    ) --[[@as function]]
    self.symbol_cache_idx = self.symbol_cache_idx + 1
    self.symbol_cache[self.symbol_cache_idx] = func -- Keep the function alive(avoid gc)

    return self.symbol_cache[self.symbol_cache_idx]
end

function DpiExporter:fetch_get_vec_value_func(hierpath)
    local info = assert(
        self:lookup(hierpath),
        "[DpiExporter] Signal " .. hierpath .. " is not exported"
    )

    local func_name = f("VERILUA_DPI_EXPORTER_%s_GET_VEC", to_hierpath_name(info.hierPath))
    local func = SymbolHelper.try_ffi_cast(
        f("void %s(uint32_t *vec);", func_name)
    ) --[[@as function]]
    self.symbol_cache_idx = self.symbol_cache_idx + 1
    self.symbol_cache[self.symbol_cache_idx] = func -- Keep the function alive(avoid gc)

    return self.symbol_cache[self.symbol_cache_idx]
end

function DpiExporter:fetch_get_hex_str_value_func(hierpath)
    local info = assert(
        self:lookup(hierpath),
        "[DpiExporter] Signal " .. hierpath .. " is not exported"
    )

    local func_name = f("VERILUA_DPI_EXPORTER_%s_GET_HEX_STR", to_hierpath_name(info.hierPath))
    local func = SymbolHelper.try_ffi_cast(
        f("void %s(char *hex_str);", func_name)
    ) --[[@as function]]
    self.symbol_cache_idx = self.symbol_cache_idx + 1
    self.symbol_cache[self.symbol_cache_idx] = func -- Keep the function alive(avoid gc)

    return self.symbol_cache[self.symbol_cache_idx]
end

return DpiExporter
