---@diagnostic disable: redundant-parameter
----------------------------------------------------
-- Auto generated by gen_chdl_access.py
-- DO NOT edit this file!
----------------------------------------------------

local vpiml = require "verilua.vpiml.vpiml"
local BitVec = require "verilua.utils.BitVec"
local table_new = require "table.new"

local assert = assert
local f = string.format
local ffi = require "ffi"
local type = type
local ffi_istype = ffi.istype
local chdl = {
    get = function(this) assert(false, f("<chdl>:get() is not implemented! fullpath => %s bitwidth => %d", this.fullpath, this.width)) end,
    get64 = function(this) assert(false, f("<chdl>:get64() is not implemented! fullpath => %s bitwidth => %d", this.fullpath, this.width)) end,
    set = function(this) assert(false, f("<chdl>:set() is not implemented! fullpath => %s bitwidth => %d", this.fullpath, this.width)) end,
    set_imm = function(this) assert(false, f("<chdl>:set_imm() is not implemented! fullpath => %s bitwidth => %d", this.fullpath, this.width)) end,
    set_unchecked = function(this) assert(false, f("<chdl>:set_unchecked() is not implemented! fullpath => %s bitwidth => %d", this.fullpath, this.width)) end,
    set_imm_unchecked = function(this) assert(false, f("<chdl>:set_imm_unchecked() is not implemented! fullpath => %s bitwidth => %d", this.fullpath, this.width)) end,
    set_bits = function(this) assert(false, f("<chdl>:set_bits() is not implemented! fullpath => %s bitwidth => %d", this.fullpath, this.width)) end,
    set_bits_imm = function(this) assert(false, f("<chdl>:set_bits_imm() is not implemented! fullpath => %s bitwidth => %d", this.fullpath, this.width)) end,
    force = function(this) assert(false, f("<chdl>:force() is not implemented! fullpath => %s bitwidth => %d", this.fullpath, this.width)) end,
    force_imm = function(this) assert(false, f("<chdl>:force_imm() is not implemented! fullpath => %s bitwidth => %d", this.fullpath, this.width)) end,
    release = function(this) assert(false, f("<chdl>:release() is not implemented! fullpath => %s bitwidth => %d", this.fullpath, this.width)) end,
    release_imm = function(this) assert(false, f("<chdl>:release_imm() is not implemented! fullpath => %s bitwidth => %d", this.fullpath, this.width)) end,
}

local chdl_array = {
    get_index = function(this) assert(false, f("Normal handle does not support <chdl>:get_index(), fullpath => %s bitwidth => %d is_array => %s", this.fullpath, this.width, tostring(this.is_array))) end,
    get_index_all = function(this) assert(false, f("Normal handle does not support <chdl>:get_index_all(), fullpath => %s bitwidth => %d is_array => %s", this.fullpath, this.width, tostring(this.is_array))) end,
    get_index_bitvec = function(this) assert(false, f("Normal handle does not support <chdl>:get_index_bitvec(), fullpath => %s bitwidth => %d is_array => %s", this.fullpath, this.width, tostring(this.is_array))) end,
    set_all = function(this) assert(false, f("Normal handle does not support <chdl>:set_all(), fullpath => %s bitwidth => %d is_array => %s", this.fullpath, this.width, tostring(this.is_array))) end,
    set_all_imm = function(this) assert(false, f("Normal handle does not support <chdl>:set_all_imm(), fullpath => %s bitwidth => %d is_array => %s", this.fullpath, this.width, tostring(this.is_array))) end,
    set_all_unchecked = function(this) assert(false, f("Normal handle does not support <chdl>:set_all_unchecked(), fullpath => %s bitwidth => %d is_array => %s", this.fullpath, this.width, tostring(this.is_array))) end,
    set_all_imm_unchecked = function(this) assert(false, f("Normal handle does not support <chdl>:set_all_imm_unchecked(), fullpath => %s bitwidth => %d is_array => %s", this.fullpath, this.width, tostring(this.is_array))) end,
}
-- Singleton methods: created once at require() time
chdl.get = function(this)
    vpiml.vpiml_get_value_multi(this.hdl, this.c_results, this.beat_num)
    return this.c_results
end

chdl.get64 = function(this)
    return vpiml.vpiml_get_value64(this.hdl)
end

chdl.get_bitvec = function(this)
    vpiml.vpiml_get_value_multi(this.hdl, this.c_results, this.beat_num)
    if this.bitvec then
        this.bitvec:_update_u32_vec(this.c_results)
        return this.bitvec
    else
        this.bitvec = BitVec(this.c_results, this.width)
        return this.bitvec
    end
end

chdl.set = function(this, value)
    local t = type(value)
    if t == "number" or (t == "cdata" and ffi_istype("uint64_t", value)) then
        vpiml.vpiml_set_value64_force_single(this.hdl, value)
    else
        if t ~= "table" then assert(false, "set() expects number, uint64_t, or table; got " .. t .. ", fullpath => " .. this.fullpath) end
        local beat_num = this.beat_num
        if #value ~= beat_num then assert(false, "len: " .. #value .. " =/= " .. this.beat_num) end

        if beat_num == 3 then
            vpiml.vpiml_set_value_multi_beat_3(this.hdl, value[1], value[2], value[3])
        elseif beat_num == 4 then
            vpiml.vpiml_set_value_multi_beat_4(this.hdl, value[1], value[2], value[3], value[4])
        elseif beat_num == 5 then
            vpiml.vpiml_set_value_multi_beat_5(this.hdl, value[1], value[2], value[3], value[4], value[5])
        elseif beat_num == 6 then
            vpiml.vpiml_set_value_multi_beat_6(this.hdl, value[1], value[2], value[3], value[4], value[5], value[6])
        elseif beat_num == 7 then
            vpiml.vpiml_set_value_multi_beat_7(this.hdl, value[1], value[2], value[3], value[4], value[5], value[6], value[7])
        elseif beat_num == 8 then
            vpiml.vpiml_set_value_multi_beat_8(this.hdl, value[1], value[2], value[3], value[4], value[5], value[6], value[7], value[8])
        else
            for i = 1, this.beat_num do
                this.c_results[i - 1] = value[i]
            end
            vpiml.vpiml_set_value_multi(this.hdl, this.c_results)
        end
    end
end

chdl.set_imm = function(this, value)
    local t = type(value)
    if t == "number" or (t == "cdata" and ffi_istype("uint64_t", value)) then
        vpiml.vpiml_set_imm_value64_force_single(this.hdl, value)
    else
        if t ~= "table" then assert(false, "set() expects number, uint64_t, or table; got " .. t .. ", fullpath => " .. this.fullpath) end
        local beat_num = this.beat_num
        if #value ~= beat_num then assert(false, "len: " .. #value .. " =/= " .. this.beat_num) end

        if beat_num == 3 then
            vpiml.vpiml_set_imm_value_multi_beat_3(this.hdl, value[1], value[2], value[3])
        elseif beat_num == 4 then
            vpiml.vpiml_set_imm_value_multi_beat_4(this.hdl, value[1], value[2], value[3], value[4])
        elseif beat_num == 5 then
            vpiml.vpiml_set_imm_value_multi_beat_5(this.hdl, value[1], value[2], value[3], value[4], value[5])
        elseif beat_num == 6 then
            vpiml.vpiml_set_imm_value_multi_beat_6(this.hdl, value[1], value[2], value[3], value[4], value[5], value[6])
        elseif beat_num == 7 then
            vpiml.vpiml_set_imm_value_multi_beat_7(this.hdl, value[1], value[2], value[3], value[4], value[5], value[6], value[7])
        elseif beat_num == 8 then
            vpiml.vpiml_set_imm_value_multi_beat_8(this.hdl, value[1], value[2], value[3], value[4], value[5], value[6], value[7], value[8])
        else
            for i = 1, this.beat_num do
                this.c_results[i - 1] = value[i]
            end
            vpiml.vpiml_set_imm_value_multi(this.hdl, this.c_results)
        end
    end
end

chdl.force = function(this, value)
    local t = type(value)
    if t == "number" or (t == "cdata" and ffi_istype("uint64_t", value)) then
        vpiml.vpiml_force_value64_force_single(this.hdl, value)
    else
        if t ~= "table" then assert(false, "set() expects number, uint64_t, or table; got " .. t .. ", fullpath => " .. this.fullpath) end
        local beat_num = this.beat_num
        if #value ~= beat_num then assert(false, "len: " .. #value .. " =/= " .. this.beat_num) end

        if beat_num == 3 then
            vpiml.vpiml_force_value_multi_beat_3(this.hdl, value[1], value[2], value[3])
        elseif beat_num == 4 then
            vpiml.vpiml_force_value_multi_beat_4(this.hdl, value[1], value[2], value[3], value[4])
        elseif beat_num == 5 then
            vpiml.vpiml_force_value_multi_beat_5(this.hdl, value[1], value[2], value[3], value[4], value[5])
        elseif beat_num == 6 then
            vpiml.vpiml_force_value_multi_beat_6(this.hdl, value[1], value[2], value[3], value[4], value[5], value[6])
        elseif beat_num == 7 then
            vpiml.vpiml_force_value_multi_beat_7(this.hdl, value[1], value[2], value[3], value[4], value[5], value[6], value[7])
        elseif beat_num == 8 then
            vpiml.vpiml_force_value_multi_beat_8(this.hdl, value[1], value[2], value[3], value[4], value[5], value[6], value[7], value[8])
        else
            for i = 1, this.beat_num do
                this.c_results[i - 1] = value[i]
            end
            vpiml.vpiml_force_value_multi(this.hdl, this.c_results)
        end
    end
end

chdl.force_imm = function(this, value)
    local t = type(value)
    if t == "number" or (t == "cdata" and ffi_istype("uint64_t", value)) then
        vpiml.vpiml_force_imm_value64_force_single(this.hdl, value)
    else
        if t ~= "table" then assert(false, "set() expects number, uint64_t, or table; got " .. t .. ", fullpath => " .. this.fullpath) end
        local beat_num = this.beat_num
        if #value ~= beat_num then assert(false, "len: " .. #value .. " =/= " .. this.beat_num) end

        if beat_num == 3 then
            vpiml.vpiml_force_imm_value_multi_beat_3(this.hdl, value[1], value[2], value[3])
        elseif beat_num == 4 then
            vpiml.vpiml_force_imm_value_multi_beat_4(this.hdl, value[1], value[2], value[3], value[4])
        elseif beat_num == 5 then
            vpiml.vpiml_force_imm_value_multi_beat_5(this.hdl, value[1], value[2], value[3], value[4], value[5])
        elseif beat_num == 6 then
            vpiml.vpiml_force_imm_value_multi_beat_6(this.hdl, value[1], value[2], value[3], value[4], value[5], value[6])
        elseif beat_num == 7 then
            vpiml.vpiml_force_imm_value_multi_beat_7(this.hdl, value[1], value[2], value[3], value[4], value[5], value[6], value[7])
        elseif beat_num == 8 then
            vpiml.vpiml_force_imm_value_multi_beat_8(this.hdl, value[1], value[2], value[3], value[4], value[5], value[6], value[7], value[8])
        else
            for i = 1, this.beat_num do
                this.c_results[i - 1] = value[i]
            end
            vpiml.vpiml_force_imm_value_multi(this.hdl, this.c_results)
        end
    end
end

chdl.set_unchecked = function(this, value)
    local t = type(value)
    if t == "number" or (t == "cdata" and ffi_istype("uint64_t", value)) then
        vpiml.vpiml_set_value64_force_single(this.hdl, value)
    else
        local beat_num = this.beat_num
        if beat_num == 3 then
            vpiml.vpiml_set_value_multi_beat_3(this.hdl, value[1], value[2], value[3])
        elseif beat_num == 4 then
            vpiml.vpiml_set_value_multi_beat_4(this.hdl, value[1], value[2], value[3], value[4])
        elseif beat_num == 5 then
            vpiml.vpiml_set_value_multi_beat_5(this.hdl, value[1], value[2], value[3], value[4], value[5])
        elseif beat_num == 6 then
            vpiml.vpiml_set_value_multi_beat_6(this.hdl, value[1], value[2], value[3], value[4], value[5], value[6])
        elseif beat_num == 7 then
            vpiml.vpiml_set_value_multi_beat_7(this.hdl, value[1], value[2], value[3], value[4], value[5], value[6], value[7])
        elseif beat_num == 8 then
            vpiml.vpiml_set_value_multi_beat_8(this.hdl, value[1], value[2], value[3], value[4], value[5], value[6], value[7], value[8])
        else
            for i = 1, this.beat_num do
                this.c_results[i - 1] = value[i]
            end
            vpiml.vpiml_set_value_multi(this.hdl, this.c_results)
        end
    end
end

chdl.set_imm_unchecked = function(this, value)
    local t = type(value)
    if t == "number" or (t == "cdata" and ffi_istype("uint64_t", value)) then
        vpiml.vpiml_set_imm_value64_force_single(this.hdl, value)
    else
        local beat_num = this.beat_num
        if beat_num == 3 then
            vpiml.vpiml_set_imm_value_multi_beat_3(this.hdl, value[1], value[2], value[3])
        elseif beat_num == 4 then
            vpiml.vpiml_set_imm_value_multi_beat_4(this.hdl, value[1], value[2], value[3], value[4])
        elseif beat_num == 5 then
            vpiml.vpiml_set_imm_value_multi_beat_5(this.hdl, value[1], value[2], value[3], value[4], value[5])
        elseif beat_num == 6 then
            vpiml.vpiml_set_imm_value_multi_beat_6(this.hdl, value[1], value[2], value[3], value[4], value[5], value[6])
        elseif beat_num == 7 then
            vpiml.vpiml_set_imm_value_multi_beat_7(this.hdl, value[1], value[2], value[3], value[4], value[5], value[6], value[7])
        elseif beat_num == 8 then
            vpiml.vpiml_set_imm_value_multi_beat_8(this.hdl, value[1], value[2], value[3], value[4], value[5], value[6], value[7], value[8])
        else
            for i = 1, this.beat_num do
                this.c_results[i - 1] = value[i]
            end
            vpiml.vpiml_set_imm_value_multi(this.hdl, this.c_results)
        end
    end
end

chdl.set_bits = function(this, s, e, v)
    local bv = this:get_bitvec():_set_bitfield(s, e, v)
    this:set_unchecked(bv.u32_vec)
end

chdl.set_bits_imm = function(this, s, e, v)
    local bv = this:get_bitvec():_set_bitfield(s, e, v)
    this:set_imm_unchecked(bv.u32_vec)
end

chdl.release = function(this)
    vpiml.vpiml_release_value(this.hdl)
end

chdl.release_imm = function(this)
    vpiml.vpiml_release_imm_value(this.hdl)
end

-- Array methods (also singleton)
chdl_array.get_index = function(this, index)
    local chosen_hdl = this.array_hdls[index + 1]
    vpiml.vpiml_get_value_multi(chosen_hdl, this.c_results, this.beat_num)
    return this.c_results
end

chdl_array.get_index_all = function(this)
    local ret = table_new(this.array_size, 0)
    for index = 0, this.array_size - 1 do
        vpiml.vpiml_get_value_multi(this.array_hdls[index + 1], this.c_results, this.beat_num)
        local tmp = table_new(this.beat_num, 0)
        for i = 1, this.beat_num do
            tmp[i] = this.c_results[i]
        end
        ret[index + 1] = tmp
    end
    return ret
end

chdl_array.get_index_bitvec = function(this, index)
    local chosen_hdl = this.array_hdls[index + 1]
    vpiml.vpiml_get_value_multi(chosen_hdl, this.c_results, this.beat_num)
    if this.array_bitvecs[index + 1] then
        this.array_bitvecs[index + 1]:_update_u32_vec(this.c_results)
        return this.array_bitvecs[index + 1]
    else
        this.array_bitvecs[index + 1] = BitVec(this.c_results, this.width)
        return this.array_bitvecs[index + 1]
    end
end

chdl_array.set_all = function(this, values)
    for index = 0, this.array_size - 1 do
        this[index]:set(values[index + 1])
    end
end

chdl_array.set_all_imm = function(this, values)
    for index = 0, this.array_size - 1 do
        this[index]:set_imm(values[index + 1])
    end
end

chdl_array.set_all_unchecked = function(this, values)
    for index = 0, this.array_size - 1 do
        this[index]:set_unchecked(values[index + 1])
    end
end

chdl_array.set_all_imm_unchecked = function(this, values)
    for index = 0, this.array_size - 1 do
        this[index]:set_imm_unchecked(values[index + 1])
    end
end

chdl.set_bits_hex_str = function(this, s, e, hex_str)
    local bv = this:get_bitvec():_set_bitfield_hex_str(s, e, hex_str)
    if this.beat_num == 1 then
        return this:set_unchecked(bv.u32_vec[1])
    end
    return this:set_unchecked(bv.u32_vec)
end

chdl.set_bits_imm_hex_str = function(this, s, e, hex_str)
    local bv = this:get_bitvec():_set_bitfield_hex_str(s, e, hex_str)
    if this.beat_num == 1 then
        return this:set_imm_unchecked(bv.u32_vec[1])
    end
    return this:set_imm_unchecked(bv.u32_vec)
end

-- Skip the VPI write when the value equals the one written by the previous
-- cached write. reset_set_cached() clears the cache.
chdl.set_cached = function(this, value)
    if this.cached_value == value then return end
    this.cached_value = value
    return this:set(value)
end

chdl.set_imm_cached = function(this, value)
    if this.cached_value == value then return end
    this.cached_value = value
    return this:set_imm(value)
end

local function deprecated(old, new)
    _G.verilua_warning("[deprecated] <chdl>:" .. old .. "() is deprecated, use " .. new .. " instead")
end

chdl.set_unsafe = function(this, value)
    deprecated("set_unsafe", "<chdl>:set_unchecked()")
    return this:set_unchecked(value)
end

chdl.set_imm_unsafe = function(this, value)
    deprecated("set_imm_unsafe", "<chdl>:set_imm_unchecked()")
    return this:set_imm_unchecked(value)
end

chdl.set_force = function(this, value)
    deprecated("set_force", "<chdl>:force()")
    return this:force(value)
end

chdl.set_imm_force = function(this, value)
    deprecated("set_imm_force", "<chdl>:force_imm()")
    return this:force_imm(value)
end

chdl.set_release = function(this)
    deprecated("set_release", "<chdl>:release()")
    return this:release()
end

chdl.set_imm_release = function(this)
    deprecated("set_imm_release", "<chdl>:release_imm()")
    return this:release_imm()
end

chdl.set_bitfield = function(this, s, e, v)
    deprecated("set_bitfield", "<chdl>:set_bits()")
    return this:set_bits(s, e, v)
end

chdl.set_imm_bitfield = function(this, s, e, v)
    deprecated("set_imm_bitfield", "<chdl>:set_bits_imm()")
    return this:set_bits_imm(s, e, v)
end

chdl.set_bitfield_hex_str = function(this, s, e, hex_str)
    deprecated("set_bitfield_hex_str", "<chdl>:set_bits_hex_str()")
    return this:set_bits_hex_str(s, e, hex_str)
end

chdl.set_imm_bitfield_hex_str = function(this, s, e, hex_str)
    deprecated("set_imm_bitfield_hex_str", "<chdl>:set_bits_imm_hex_str()")
    return this:set_bits_imm_hex_str(s, e, hex_str)
end

chdl_array.at = function(this, idx)
    deprecated("at", "<chdl>[index]")
    return this[idx]
end

chdl_array.set_index = function(this, index, value)
    deprecated("set_index", "<chdl>[index]:set()")
    return this[index]:set(value)
end

chdl_array.set_imm_index = function(this, index, value)
    deprecated("set_imm_index", "<chdl>[index]:set_imm()")
    return this[index]:set_imm(value)
end

chdl_array.set_index_unsafe = function(this, index, value)
    deprecated("set_index_unsafe", "<chdl>[index]:set_unchecked()")
    return this[index]:set_unchecked(value)
end

chdl_array.set_imm_index_unsafe = function(this, index, value)
    deprecated("set_imm_index_unsafe", "<chdl>[index]:set_imm_unchecked()")
    return this[index]:set_imm_unchecked(value)
end

chdl_array.set_index_bitfield = function(this, index, s, e, v)
    deprecated("set_index_bitfield", "<chdl>[index]:set_bits()")
    return this[index]:set_bits(s, e, v)
end

chdl_array.set_imm_index_bitfield = function(this, index, s, e, v)
    deprecated("set_imm_index_bitfield", "<chdl>[index]:set_bits_imm()")
    return this[index]:set_bits_imm(s, e, v)
end

chdl_array.set_index_bitfield_hex_str = function(this, index, s, e, hex_str)
    deprecated("set_index_bitfield_hex_str", "<chdl>[index]:set_bits_hex_str()")
    return this[index]:set_bits_hex_str(s, e, hex_str)
end

chdl_array.set_imm_index_bitfield_hex_str = function(this, index, s, e, hex_str)
    deprecated("set_imm_index_bitfield_hex_str", "<chdl>[index]:set_bits_imm_hex_str()")
    return this[index]:set_bits_imm_hex_str(s, e, hex_str)
end

chdl_array.set_index_all = function(this, values)
    deprecated("set_index_all", "<chdl>:set_all()")
    return this:set_all(values)
end

chdl_array.set_imm_index_all = function(this, values)
    deprecated("set_imm_index_all", "<chdl>:set_all_imm()")
    return this:set_all_imm(values)
end

chdl_array.set_index_unsafe_all = function(this, values)
    deprecated("set_index_unsafe_all", "<chdl>:set_all_unchecked()")
    return this:set_all_unchecked(values)
end

chdl_array.set_imm_index_unsafe_all = function(this, values)
    deprecated("set_imm_index_unsafe_all", "<chdl>:set_all_imm_unchecked()")
    return this:set_all_imm_unchecked(values)
end

-- Pre-built combined table (methods + array_methods merged at load time)
local M_combined = {}
for k, v in pairs(chdl) do M_combined[k] = v end
for k, v in pairs(chdl_array) do M_combined[k] = v end

return function(is_array)
    return is_array and M_combined or chdl
end
