#!/usr/bin/env python3

import os
import sys
import subprocess
import shutil

RED = "\033[31m"
GREEN = "\033[32m"
YELLOW = "\033[33m"
BLUE = "\033[34m"
RESET = "\033[0m"

verilua_path = os.getenv("VERILUA_HOME")
assert verilua_path != None, "[vl-iverilog] cannot find VERILUA_HOME!"

luapath = verilua_path + "/luajit-pro/luajit2.1"
libpath = verilua_path + "/shared"
liblua_path = luapath + "/lib"

assert os.path.exists(liblua_path + "/libluajit-5.1.so"), "[vl-iverilog] cannot find liblua in " + liblua_path
assert os.path.exists(libpath + "/libverilua_iverilog.so"), "[vl-iverilog] cannot find libverilua_iverilog.so in " + libpath

iverilog = shutil.which("iverilog")
assert iverilog != None, "[vl-iverilog] cannot find `iverilog` in PATH"

cmd_list = [iverilog] + ["-g2012"] + sys.argv[1:]
cmd = " ".join(cmd_list)

print(f'''
[{YELLOW}vl-iverilog{RESET}] cmd:
{GREEN}{cmd}{RESET}
''', flush = True)

exit(subprocess.call(cmd_list))
