local PWD = os.getenv("PWD")

target("generate_wave")
    add_rules("verilua")
    -- add_toolchains("@iverilog") -- use iverilog
    add_toolchains("@verilator") -- use verilator

    add_files("./Counter.v")
    
    set_values("cfg.lua_main", "./LuaMain.lua")
    set_values("cfg.top", "Counter")

    after_run(function (target)
        -- copy the generated wave file into the current directory after target has been run
        -- os.cp(PWD .. "/build/iverilog/Counter/wave/test.vcd", PWD) -- use iverilog
        os.cp(PWD .. "/build/verilator/Counter/wave/test.vcd", PWD) -- use verilator
    end)

target("simulate_wave")
    add_rules("verilua")
    add_toolchains("@wave_vpi")

    add_files("./test.vcd") -- this wave file is generated by <generate_wave> target
    
    set_values("cfg.lua_main", "./LuaMainForWave.lua")
    set_values("cfg.top", "Counter")

