name: Test Verilua
on:
  push:
    branches:
      - test-ci

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: '2.9.9'

      - name: Setup rust
        uses: actions-rs/toolchain@v1
        with:
            profile: minimal
            toolchain: stable
            override: true

      - name: Setup conan
        uses: imesense/gha-setup-conan@v0.1
        with:
          version: '2.14.0'

      - name: Create conan default profile
        run: conan profile detect --force

      - uses: veryl-lang/setup-verilator@v1
        with:
          version: 5.028

      - name: Check cargo
        run: cargo --version

      - name: Check xmake
        run: xmake --version

      - name: Check conan
        run: conan --version

      - name: Check verilator
        run: verilator --version

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      
      - name: Install verilua
        run: |
          xmake install verilua
        
      - name: Test verilua
        run: |
          xmake r test

